//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid SimpleEnemyAI = new Guid("7cad78a0-5210-4d36-a9c7-c9ce07a2b05d");

    }
}
